version: '3.7'
services:
  app_test:
    container_name: full_app_test
    build:
      context: .
      dockerfile: ./Dockerfile.test
    volumes:
      - api_test:/api/
    depends_on:
      - postgres_test
      # - mysql_test
    networks:
      - fullstack_test

  postgres_test:
    image: postgres:latest
    container_name: full_db_test_postgress
    environment:
      - POSTGRES_USER=${TEST_DB_USER}  
      - POSTGRES_PASSWORD=${TEST_DB_PASSWORD}
      - POSTGRES_DB=${TEST_DB_NAME}
      - DATABASE_HOST=${TEST_DB_HOST} 
    ports:
      - '5555:5432'
    volumes:
      - database_postgres_test:/var/lib/postgresql/data
    networks:
      - fullstack_test

volumes:
  api_test:
  database_postgres_test:

networks:
  fullstack_test:
    driver: bridge